### PR TITLE
🚸 Remove false positive (www.)ip-api.com

### PR DESCRIPTION
**Pull request by thomasmerz**
This PR removes (www.)ip-api.com which is a false positive (and I really don't know WHY and HOW children should or would use this domain!? 😜). It has been also removed from other major blocklists:
https://blocklist-tools.developerdan.com/entries/search?q=ip-api.com

I will also inform the owners of the remaining lists to remove this domain(s).

Because of this blocklist entry, someone isn't able to gather ASN infos for a given IP or domain 😞 
```
# https://github.com/trimstray/the-book-of-secret-knowledge#shell-functions-toc
function getASN () {
    local _ip="$1";
    local _curl_base="curl --request GET";
    local _timeout="15";
    _asn=$($_curl_base -ks -m "$_timeout" "http://ip-api.com/line/${_ip}?fields=as");
    _state=$(echo $?);
    if [[ -z "$_ip" ]] || [[ "$_ip" == "null" ]] || [[ "$_state" -ne 0 ]]; then
        echo -en "Unsuccessful ASN gathering.\\n";
    else
        echo -en "$_ip > $_asn\\n";
    fi
}
```

### CODE REVIEW

**Comment by lightswitch05** [comment]
There is a much larger discussions of these types of websites here: https://github.com/lightswitch05/hosts/issues/281

**Comment by thomasmerz** [comment]
@lightswitch05 , but there's no final conclusion or even solution mentioned!? 😲

**Comment by lightswitch05** [comment]
The solution is to add it to an allow list on your side if you want to allow it. I'm not sure how you are using my list, but surely it provides a way to specify allowing specific entries?

**Comment by thomasmerz** [comment]
I'm using the `extended` ads and tracking list - not the `aggressive` one which already says "do not use it unless you are willing to maintain your own whitelist". Because so many other blocklists (see link above and [here](https://github.com/pulls?q=is%3Aopen+is%3Apr+author%3Athomasmerz+archived%3Afalse+ip-api.com)) already removed `ip-api.com` from their blocklists I would suggest moving them `extended` to `aggressive`.

Do you agree for a new PR with this change?

**Pull request closed without merging**
