### PR TITLE
Added first iteration of logo

### PR DESCRIPTION
**Pull request by lightswitch05**
See: https://github.com/lightswitch05/hosts/blob/feature/create-logo/README.md

Inspiration: [They Live](https://www.youtube.com/watch?v=jTK8eff1Zsk) 

[Hosts Logo](https://www.github.developerdan.com/hosts/)

### CODE REVIEW

**Comment by lightswitch05** [comment]
I'm not a graphic editor and don't really know what I'm doing here. Would love some help if anyone has the time. The SVG looks like junk in my GitHub app for some reason.

**Comment by llacb47** [comment]
sumbit - typo

**Comment by lightswitch05** [comment]
@llacb47 also 'coform', thank you!

**Comment by lightswitch05** [comment]
I like this idea a lot better then my current logo, but without commissioning a legit artist to make it, its just not going to happen. I just can't justify the cost for a project I do for free on my spare time, and its just a hosts project anyway.

**Pull request closed without merging**
