### PR TITLE
Automatic updates

### PR DESCRIPTION
**Pull request by lightswitch05**
I'd like to ask everyone's opinion on this pull request and an issue I've been contemplating. My hosts list has always been automatically expanded to discover subdomains of blocked hosts. Originally, it only used [Certificate Transparency Logs](https://en.wikipedia.org/wiki/Certificate_Transparency) for subdomain discovery. However, the results were somewhat limited due to wildcard certificates or simply no certs at all for a domain. Not too long ago I added [VirusTotal](http://virustotal.com/) as another source for subdomain discovery.

VirusTotal regularly scans websites and provides a free API to query for domain details including the last 100 subdomains discovered. This works great for finding all sorts of subdomains and regularly includes up-to-date information. Unfortunately it works a little too good.

Since a lot of spammer domains are now using random or one-time subdomain names, I had to update my whitelist logic to use regular expressions, for example: [online-matrix.net](https://github.com/lightswitch05/hosts/blob/master/ads-and-tracking-whitelist.txt#L49-L50). This works good for whitelisting, but I'm left trying to decide which subdomains are random and should be whitelisted and which domains just have a random-looking subdomain and are valid to block. For example, I believe Double Click subdomains like `3226898.fls.doubleclick.net` **should** remain blocked. There are a ton of doubleclick subdomains, but I do not believe they rotate often when added to a website and that the number is just an account id - not random. And then there are subdomains like `08vqf-asj2b.ads.tremorhub.com` which look very random... I have no idea if they are like doubleclick where they get reused often or if it is a random domain that will never be seen again.

Alright, so long story story short - I'm left with a large and very quickly growing hosts file. This pull request alone adds 1,431 to the standard ads and tracking list - and it grows by hundreds each time I run the expansion script.

# Questions

* Is this pull request good or bad?
* What new regular expressions should be added to trim the list down some?
* Is there a better way to reduce ads and tracking at a network level? (I use this list with my Pi-Hole)

----
Note: I value your opinions and want to find a solution that makes everyone happy. But at the end of the day, I manage this hosts list for myself and my family so the final decision on how to handle this is up to me.

----

# TODO

* [ ] Create a flat-file database to track first seen, last seen, and source for each auto-expanded domain
    * sources: crt, virustotal, list. For initial population, anything that cannot be discovered via crt should default to virustotal
    * Only expanded domains can expire- domains on a base list should never expire
* [ ] Add a date range filter on all crt lookups to allow old domains to drop off discovery. Perhaps filter by active certs only

### CODE REVIEW

**Comment by StevenBlack** [comment]
@lightswitch05 I'd love to see a compensatory mechanism whereby domain audit tools could identify ones no longer in use.  In other words, curation mechanisms that cull obsolete domains.

Because a cumulation-only system isn't sustainable because host files have practical, finite size limits.

**Comment by lightswitch05** [comment]
Thanks for the input Steven, I think you are right. Just because a subdomain was discovered one day, doesn't mean it should remain until the heat death of the universe. For certificate based subdomain discoveries, I should be able to add a date range on the lookup. The VirusTotal ones get a bit more complicated. I'll see if I can't think of some way to keep track of when subdomains were first added, last seen, and a maximum life span.

To implement something like this is going to take some time 🕐

**Comment by anudeepND** [comment]
@lightswitch05 One thing, you can remove domains like `docs.baddomain.com`, `help.baddomain.com`, `api-docs.baddomain.com`, `support.baddomain.com`, `contact.baddomain.com` and so on...

99% domain doesn't do tracking or serving ads. However only a few domains can be removed, but this will keep the host file tidy. What do you think?

**Comment by lightswitch05** [comment]
@anudeepND yes those are good additions. I have a regex list of domain prefixes to ignore. I'll add those to it https://github.com/lightswitch05/hosts/blob/9099c50affd8fd4391173a26b7ea6fc718524953/ads-and-tracking-whitelist.txt#L73-L96

**Pull request merged**
