### PR TITLE
Massive update using the vendor list - help wanted!

### PR DESCRIPTION
**Pull request by lightswitch05**
Massive update using the vendor list found here https://github.com/lightswitch05/hosts/issues/102#issuecomment-535524023 - so far only got to ID 1313.

This is a massive list update and it is bound to have some false positives in it. **I would be very grateful to anyone willing to use this updated blocklist for the next few weeks and report back any issues.** So far I've only added about a little under half of the full list - so more updates to this pull request coming over the next few days.

Link to use for testing over the next few weeks: https://raw.githubusercontent.com/lightswitch05/hosts/feature/hosts-from-vendor-list/ads-and-tracking-extended.txt

### CODE REVIEW

**Comment by baujahr** [comment]
```
pciins-033.inscname.net
d2v02itv0y9u9t.cloudfront.net
a054.zamnetwork.inscname.net
a-h2-instartops-002.insnw.net
```
Blocking of these domains breaks stylesheet on https://wowhead.com

**Comment by baujahr** [comment]
Blocking 
`googleadapis.l.google.com`
indirectly also blocks
`fonts.googleapis.com`

**Comment by lightswitch05** [comment]
```
googleadapis.l.google.com
gstaticadssl.l.google.com
```

These are blocked in the primary list already and not related to this pull request. Fonts are a fine line between functionality and tracking- I'm leaning on the side that I would rather have these ad hosts blocked. You could open another ticket for these and I could leave it open for tracking, but its not related to this pull request

**Comment by lightswitch05** [comment]
```
pciins-033.inscname.net
d2v02itv0y9u9t.cloudfront.net
a054.zamnetwork.inscname.net
a-h2-instartops-002.insnw.net
```

These are also already blocked in the master branch - so also not related to this pull request and need to be tracked elsewhere

**Comment by dnmTX** [comment]
@lightswitch05 

> These are blocked in the primary list already and not related to this pull request. Fonts are a fine line between functionality and tracking- I'm leaning on the side that I would rather have these ad hosts blocked.....

Apparently some DNS Resolvers are blocking not only the listed domain but it's CNAME as well.
In this case `googleadapis.l.google.com` is the CNAME of `fonts.googleapis.com`.
Refer to this [issue](https://github.com/anudeepND/blacklist/issues/57) for more info and i believe there is another one with the same complaint in StevenBlack's repo. 
I'm not saying **remove it**,just keep in mind for the feature and for your reference. 👍

**Comment by lightswitch05** [comment]
My plan was to fully get through the list before merging this. But at this rate, its never going to happen. I'm going to go ahead and merge this and open up another pull request in the future when I get back to it

**Pull request merged**
